#!/usr/bin/env python3

"""
Regression Test: J2 Perturbation Validation

This regression test validates the PROTOS dynamics propagation against a
trusted reference solution generated by NASA's General Mission Analysis Tool (GMAT).
The test compares the final propagated state vector produced by PROTOS to
the GMAT reference state for a single spacecraft under a basic Earth gravity model
that includes the J2 zonal harmonic perturbation.

Objective:
    Verify that the PROTOS dynamics module accurately reproduces the
    position and velocity evolution under a central Earth gravity field
    with J2 perturbations.

Procedure:
    1. Load simulation configuration from 'J2_regression_test.jsonx'.
    2. Propagate the spacecraft state using the PROTOS dynamics engine.
    3. Compare the final propagated state vector to the GMAT-generated
       reference state after the same simulation duration.
    4. Pass criterion: final state error norm is within predefined tolerance.

Reference:
    - NASA GMAT (https://gmatcentral.org/)
    - Gravity Model: Point-mass Earth + J2 zonal harmonic term

This test ensures consistency between PROTOS dynamics and GMAT baseline results
for Earth orbit propagation including second zonal harmonic perturbations.
"""

import os
import sys
import numpy as np


# -------------------------------------------------------------------
# Setup paths so script can be run from any directory
# -------------------------------------------------------------------
SCRIPT_DIR = os.path.dirname(os.path.abspath(__file__))
PROJECT_ROOT = os.path.abspath(os.path.join(SCRIPT_DIR, ".."))
sys.path.append(PROJECT_ROOT)

from src import io_utils, dynamics, gnc

def main():
    # 1. Parse input
    config = io_utils.parse_input("data/input_files/twobody_regression_test.jsonx")
    dyn_config = config["dynamics"]
    gnc_config = config["gnc"]

    # Extract simulation parameters
    sim = dyn_config.get("simulation", {})
    dt = sim.get("time_step", 1)
    duration = sim.get("duration", 3600.0)
    steps = int(duration / dt) + 1
    t_eval = np.linspace(0, duration, steps)

    # 2. Initialize state
    state = {
        "chief_r": np.array(dyn_config["chief_r"]),
        "chief_v": np.array(dyn_config["chief_v"]),
        "deputy_r": np.array(dyn_config["deputy_r"]),
        "deputy_v": np.array(dyn_config["deputy_v"]),
        "deputy_rho": np.array(dyn_config["deputy_rho"]),
        "deputy_rho_dot": np.array(dyn_config["deputy_rho_dot"]),
    }

    # 3. Propagate dynamics
    for _ in t_eval:
        next_state = dynamics.step(state, dt, dyn_config)
        gnc_out = gnc.step(next_state, gnc_config)
        state = next_state

    # 4. Extract final propagated state
    chief_final = np.hstack([state["chief_v"], state["chief_r"]])
    deputy_final = np.hstack([state["deputy_v"], state["deputy_r"]])
    propagated_state = np.hstack([chief_final, deputy_final])

    # -------------------------------------------------------------------
    # 5. GMAT reference state (EarthICRF, includes J2)
    # -------------------------------------------------------------------
    gmat_truth = np.array([
        # Chief: VX, VY, VZ, X, Y, Z
        6.686307616893356,  1.899552538319278, -2.198082485525997,
        768.0744712532941, -6639.910257356953, -3401.744868705216,
        # Deputy: VX, VY, VZ, X, Y, Z
        6.253471443356108,  1.159847348912309, -2.473254755578088,
        -1.145106217852843, -7316.696315342869, -3222.243206830367
    ])


    # 6. Compare final propagated state to GMAT truth
    diff = propagated_state - gmat_truth
    position_error_km = np.linalg.norm(diff[3:6])  # Chief position error
    velocity_error_km_s = np.linalg.norm(diff[0:3])
    deputy_position_error_km = np.linalg.norm(diff[9:12])
    deputy_velocity_error_km_s = np.linalg.norm(diff[6:9])

    # -------------------------------------------------------------------
    # 7. Print comparison summary
    # -------------------------------------------------------------------
    print("\n=== J2 Regression Test: GMAT Comparison ===")
    print(f"{'State Component':<25}{'PROTOS Value':>20}{'GMAT Value':>20}{'Δ (Error)':>20}")
    print("-" * 85)
    labels = [
        "Chief.VX", "Chief.VY", "Chief.VZ", "Chief.X", "Chief.Y", "Chief.Z",
        "Deputy.VX", "Deputy.VY", "Deputy.VZ", "Deputy.X", "Deputy.Y", "Deputy.Z"
    ]
    for i, label in enumerate(labels):
        print(f"{label:<25}{propagated_state[i]:>20.6f}{gmat_truth[i]:>20.6f}{diff[i]:>20.6e}")

    print("\n--- Summary ---")
    print(f"Chief position error (km): {position_error_km:.6e}")
    print(f"Chief velocity error (km/s): {velocity_error_km_s:.6e}")
    print(f"Deputy position error (km): {deputy_position_error_km:.6e}")
    print(f"Deputy velocity error (km/s): {deputy_velocity_error_km_s:.6e}")

    tolerance_pos = 1e-1   # km
    tolerance_vel = 1e-4   # km/s

    passed = (
        position_error_km < tolerance_pos
        and velocity_error_km_s < tolerance_vel
        and deputy_position_error_km < tolerance_pos
        and deputy_velocity_error_km_s < tolerance_vel
    )

    print("\nTest Result:", "✅ PASSED" if passed else "❌ FAILED")

if __name__ == "__main__":
    main()
