#!/usr/bin/env python3

"""
Regression Test: J2 Perturbation Validation

This regression test validates the PROTOS dynamics propagation against a
trusted reference solution generated by NASA's General Mission Analysis Tool (GMAT).
The test compares the final propagated state vector produced by PROTOS to
the GMAT reference state for a single spacecraft under a basic Earth gravity model
that includes the J2 zonal harmonic perturbation.

Objective:
    Verify that the PROTOS dynamics module accurately reproduces the
    position and velocity evolution under a central Earth gravity field
    with J2 perturbations.

Procedure:
    1. Load simulation configuration from 'J2_regression_test.jsonx'.
    2. Propagate the spacecraft state using the PROTOS dynamics engine.
    3. Compare the final propagated state vector to the GMAT-generated
       reference state after the same simulation duration.
    4. Pass criterion: final state error norm is within predefined tolerance.

Reference:
    - NASA GMAT (https://gmatcentral.org/)
    - Gravity Model: Point-mass Earth + J2 zonal harmonic term

This test ensures consistency between PROTOS dynamics and GMAT baseline results
for Earth orbit propagation including second zonal harmonic perturbations.
"""

import os
import sys


# -------------------------------------------------------------------
# Setup paths so script can be run from any directory
# -------------------------------------------------------------------
SCRIPT_DIR = os.path.dirname(os.path.abspath(__file__))
PROJECT_ROOT = os.path.abspath(os.path.join(SCRIPT_DIR, ".."))
sys.path.append(PROJECT_ROOT)

import numpy as np
from datetime import timedelta
from src import dynamics, gnc
from src.io_utils import init_PROTOS
from utils.six_dof_utils import update_state_with_gnc


def main():
    # --- Initialization ---
    config = init_PROTOS.parse_input("data/input_files/j2_regression_test.jsonx")
    sim_config = config["simulation"]
    dyn_config = config["dynamics"]
    gnc_config = config["gnc"]

    dt = sim_config.get("time_step", 1)
    t_eval = np.array(config.get("t_eval"))
    initial_epoch = sim_config.get("epoch")
    is_6dof = sim_config.get("simulation_mode", "3DOF").upper() == "6DOF"

    state = config.get("init_state", {})
    trajectory = [state.copy()]
    gnc_results = []

    # --- Propagation Loop ---
    for _ in t_eval[:-1]:
        # GNC Step
        gnc_out = gnc.gnc_step(state, gnc_config)
        gnc_results.append(gnc_out)

        # Update State with GNC Outputs
        update_state_with_gnc(state, gnc_out, is_6dof)

        # Dynamics Step
        next_state = dynamics.dyn_step(dt, state, dyn_config)

        # Update Time & Epoch
        next_state["sim_time"] = np.array(state.get("sim_time", 0.0) + dt, dtype=np.float64)
        next_state["epoch"] = state.get("epoch", initial_epoch) + timedelta(seconds=dt) # type: ignore

        # Store & Advance
        trajectory.append(next_state)
        state = next_state

    # --- Extract final propagated state ---
    propagated_state = np.array([
        state["chief_v"][0], state["chief_v"][1], state["chief_v"][2],
        state["chief_r"][0], state["chief_r"][1], state["chief_r"][2],
        state["deputy_v"][0], state["deputy_v"][1], state["deputy_v"][2],
        state["deputy_r"][0], state["deputy_r"][1], state["deputy_r"][2]
    ])

    # -------------------------------------------------------------------
    # 5. GMAT reference state (EarthICRF, includes J2)
    # -------------------------------------------------------------------
    gmat_truth = np.array([
        # Chief: VX, VY, VZ, X, Y, Z
        6.691715863608378,  1.913382026344799,  -2.190196736521058,
        776.9633926691258, -6630.414731394075, -3404.054692446019,
        # Deputy: VX, VY, VZ, X, Y, Z
        6.259263250134473,  1.172024245152723,  -2.46844230284356,
        6.959710051357102, -7308.410536584149, -3225.782059722917
    ])

    # 6. Compare final propagated state to GMAT truth
    diff = propagated_state - gmat_truth
    position_error_km = np.linalg.norm(diff[3:6])  # Chief position error
    velocity_error_km_s = np.linalg.norm(diff[0:3])
    deputy_position_error_km = np.linalg.norm(diff[9:12])
    deputy_velocity_error_km_s = np.linalg.norm(diff[6:9])

    # -------------------------------------------------------------------
    # 7. Print comparison summary
    # -------------------------------------------------------------------
    print("\n=== J2 Regression Test: GMAT Comparison ===")
    print(f"{'State Component':<25}{'PROTOS Value':>20}{'GMAT Value':>20}{'Δ (Error)':>20}")
    print("-" * 85)
    labels = [
        "Chief.VX", "Chief.VY", "Chief.VZ", "Chief.X", "Chief.Y", "Chief.Z",
        "Deputy.VX", "Deputy.VY", "Deputy.VZ", "Deputy.X", "Deputy.Y", "Deputy.Z"
    ]
    for i, label in enumerate(labels):
        print(f"{label:<25}{propagated_state[i]:>20.6f}{gmat_truth[i]:>20.6f}{diff[i]:>20.6e}")

    print("\n--- Summary ---")
    print(f"Chief position error (km): {position_error_km:.6e}")
    print(f"Chief velocity error (km/s): {velocity_error_km_s:.6e}")
    print(f"Deputy position error (km): {deputy_position_error_km:.6e}")
    print(f"Deputy velocity error (km/s): {deputy_velocity_error_km_s:.6e}")

    tolerance_pos = 1e-3   # km ( 1 m)
    tolerance_vel = 1e-6   # km/s (1 mm/s)

    passed = (
        position_error_km < tolerance_pos
        and velocity_error_km_s < tolerance_vel
        and deputy_position_error_km < tolerance_pos
        and deputy_velocity_error_km_s < tolerance_vel
    )

    print("\nTest Result:", "✅ PASSED" if passed else "❌ FAILED")

if __name__ == "__main__":
    main()
