#!/usr/bin/env python3

"""
Regression Test: Two Body Validation

This regression test validates the PROTOS dynamics propagation against a
trusted reference solution generated by NASA's General Mission Analysis Tool (GMAT).
The test compares the final propagated state vector produced by PROTOS to
the GMAT reference state for a single spacecraft under a basic nonlinear Earth gravity model.

Objective:
    Verify that the PROTOS dynamics module accurately reproduces the
    position and velocity evolution under a central Earth gravity field.
    
Procedure:
    1. Load simulation configuration from 'twobody_regression_test.jsonx'.
    2. Propagate the spacecraft state using the PROTOS dynamics engine.
    3. Compare the final propagated state vector to the GMAT-generated
       reference state after the same simulation duration.
    4. Pass criterion: final state error norm is within predefined tolerance.

Reference:
    - NASA GMAT (https://gmatcentral.org/)
    - Gravity Model: Point-mass Earth

This test ensures consistency between PROTOS dynamics and GMAT baseline results
for Earth orbit propagation.
"""

import os
import sys

# -------------------------------------------------------------------
# Setup paths so script can be run from any directory
# -------------------------------------------------------------------
SCRIPT_DIR = os.path.dirname(os.path.abspath(__file__))
PROJECT_ROOT = os.path.abspath(os.path.join(SCRIPT_DIR, ".."))
sys.path.append(PROJECT_ROOT)

import copy
import numpy as np
from datetime import timedelta
from src import dynamics, gnc
from src.io_utils import init_PROTOS
from utils.six_dof_utils import update_state_with_gnc


def main():
    # --- Initialization ---
    config = init_PROTOS.init_PROTOS("data/tests/twobody_regression_test.jsonx")
    sim_config = config["simulation"]
    gnc_config = config["gnc"]

    dt = sim_config.time_step
    t_eval = sim_config.t_eval
    initial_epoch = sim_config.epoch
    is_6dof = sim_config.simulation_mode.upper() == "6DOF"

    # Initialize states
    state = config.get("init_state", {})
    
    state["epoch"] = initial_epoch
    state["chief"]["epoch"] = initial_epoch
    for sat in state["deputies"].values():
        sat["epoch"] = initial_epoch

    trajectory = [copy.deepcopy(state)]
    gnc_results = []

    # --- Propagation Loop ---
    for _ in t_eval[:-1]:
        # GNC Step
        gnc_out = gnc.gnc_step(state, gnc_config)
        gnc_results.append(copy.deepcopy(gnc_out))

        # Update State with GNC Outputs
        update_state_with_gnc(state, gnc_out, is_6dof)

        # Dynamics Step (Pass the full config dict!)
        next_state = dynamics.dyn_step(dt, state, config)

        # Update Epoch
        next_epoch = state.get("epoch", initial_epoch) + timedelta(seconds=dt)
        next_state["epoch"] = next_epoch
        next_state["chief"]["epoch"] = next_epoch
        for sat in next_state["deputies"].values():
            sat["epoch"] = next_epoch

        # Store & Advance
        trajectory.append(copy.deepcopy(next_state))
        state = next_state

    # --- Extract final propagated state ---
    chief = state["chief"]
    
    # Grab the first (and presumably only) deputy for this regression test
    deputy = list(state["deputies"].values())[0]

    propagated_state = np.array([
        chief["v"][0],  chief["v"][1],  chief["v"][2],
        chief["r"][0],  chief["r"][1],  chief["r"][2],
        deputy["v"][0], deputy["v"][1], deputy["v"][2],
        deputy["r"][0], deputy["r"][1], deputy["r"][2]
    ])

    # -------------------------------------------------------------------
    # 5. GMAT reference state (EarthICRF, Point-mass Earth)
    # -------------------------------------------------------------------
    gmat_truth = np.array([
        # Chief: VX, VY, VZ, X, Y, Z
        6.686307616893356,  1.899552538319278, -2.198082485525997,
        768.0744712532941, -6639.910257356953, -3401.744868705216,
        # Deputy: VX, VY, VZ, X, Y, Z
        6.253471443356108,  1.159847348912309, -2.473254755578088,
        -1.145106217852843, -7316.696315342869, -3222.243206830367
    ])

    # 6. Compare final propagated state to GMAT truth
    diff = propagated_state - gmat_truth
    position_error_km = np.linalg.norm(diff[3:6])  # Chief position error
    velocity_error_km_s = np.linalg.norm(diff[0:3])
    deputy_position_error_km = np.linalg.norm(diff[9:12])
    deputy_velocity_error_km_s = np.linalg.norm(diff[6:9])

    # -------------------------------------------------------------------
    # 7. Print comparison summary
    # -------------------------------------------------------------------
    print("\n=== Two Body Regression Test: GMAT Comparison ===")
    print(f"{'State Component':<25}{'PROTOS Value':>20}{'GMAT Value':>20}{'Δ (Error)':>20}")
    print("-" * 85)
    labels = [
        "Chief.VX", "Chief.VY", "Chief.VZ", "Chief.X", "Chief.Y", "Chief.Z",
        "Deputy.VX", "Deputy.VY", "Deputy.VZ", "Deputy.X", "Deputy.Y", "Deputy.Z"
    ]
    for i, label in enumerate(labels):
        print(f"{label:<25}{propagated_state[i]:>20.6f}{gmat_truth[i]:>20.6f}{diff[i]:>20.6e}")

    print("\n--- Summary ---")
    print(f"Chief position error (km): {position_error_km:.6e}")
    print(f"Chief velocity error (km/s): {velocity_error_km_s:.6e}")
    print(f"Deputy position error (km): {deputy_position_error_km:.6e}")
    print(f"Deputy velocity error (km/s): {deputy_velocity_error_km_s:.6e}")

    tolerance_pos = 1e-4   # km (10 cm)
    tolerance_vel = 1e-7   # km/s ( 0.1 mm/s)

    passed = (
        position_error_km < tolerance_pos
        and velocity_error_km_s < tolerance_vel
        and deputy_position_error_km < tolerance_pos
        and deputy_velocity_error_km_s < tolerance_vel
    )

    print("\nTest Result:", "✅ PASSED" if passed else "❌ FAILED")

if __name__ == "__main__":
    main()